blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Having doubts or questions?
    url: https://gitlab.com/disa12311/game-booster/-/issues
    about: Create an issue and get help from other members of the community
  - name: ðŸ“š Check the documentation
    url: https://gitlab.com/disa12311/game-booster/-/wikis/home
    about: Read the documentation for guides and troubleshooting
